#!/bin/bash
#PBS -N gapit
#PBS -l select=1:ncpus=4:mem=100gb:interconnect=1g,walltime=8:00:00
#PBS -o gapit.out
#PBS -e gapit.err

cd /scratch2/spower2/scripts/v2scripts/MAF_filtered

source activate r_env
# PHENOTYPE="yield"
# mkdir $PHENOTYPE
# cd $PHENOTYPE
# ln -s ../${PHENOTYPE}.csv
# ln -s ../Lentil.knn_impute.scaffold_filtered.hmp.txt
# cp gapit.R ./$PHENOTYPE # edit accordingly

Rscript gapit.AllPheno.R
